version: '3'

services:
  client: 
    build: ./client
    working_dir: /app
    command: pnpm start
    ports:
      - 3000:3000
    depends_on:
      - db
    
  server:
    build: ./backend
    working_dir: /app
    command: pnpm start
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgres/db_data
    