version: '3'

services:
  client: 
    build: ./client
    working_dir: /app
    command: pnpm start
    ports:
      - 3000:3000
    
  server:
    build: ./backend
    working_dir: /app
    command: pnpm start
    ports:
      - 8000:8000
    